import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Rimu Timber',
      category: 'Timber',
      image: '/images/p1.jpg',
      price: 13.00,
      countInStock: 10,
      brand: 'No brand',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Stainless Steel Sink',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'No brand',
      rating: 4.0,
      numReviews: 10,
      description: 'top notch sink',
    },
    {
      name: 'Outside Door',
      category: 'doors',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'No brand',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Eletric Lights',
      category: 'electrical',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'No brand',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Aluminium Ranchslider',
      category: 'Ranchslider',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'No brand',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Small toilet pan',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 10,
      countInStock: 12,
      brand: 'No brand',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality toilet pan, suitable for all',
    },
  ],
};
export default data;
